services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
    # We only pass the arguments, not the path to the file

    command:
      - serve
      - --http=0.0.0.0:8080
      - --dir=/pb_data
      - --hooksDir=/pb_hooks
